version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: mercicle/microservice-project:reverseproxy
  backend_user:
    build:
      context: ../../backend-user-api
    image: mercicle/microservice-project:udagram-backend-user
  backend_feed:
    build:
      context: ../../backend-feed-api
    image: mercicle/microservice-project:udagram-backend-feed
  frontend:
    build:
      context: ../../frontend
    image: mercicle/microservice-project:udagram-frontend
